routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
<<<<<<< HEAD
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\QuizController;
=======
>>>>>>> 3435db419e1b57988185f5d2060c78375189396d
use App\Http\Middleware\Authenticate;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

<<<<<<< HEAD
//user-related
=======
Route::get('/test', function () {
    return view('test');
});


>>>>>>> 3435db419e1b57988185f5d2060c78375189396d
Route::get('/user/{id}', [UserController::class, 'show'])->name('profile');
Route::get('/user/edit/{id}', [UserController::class, 'edit'])->name('edit-user');
Route::post('/user/update/{id}', [UserController::class, 'update'])->name('update-user');

<<<<<<< HEAD
//tik prisijungusiems
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/leaderboard', [UserController::class, 'leaderboard'])->name('leaderboard');

    Route::get('/create', [QuestionController::class, 'index'])->name('create-question');
    Route::post('/create-question', [QuestionController::class, 'store']);
    Route::group(['middleware' => ['web']], function () {
        Route::get('/game', [QuizController::class, 'quiz'])->name('question');

        Route::get('/getseed', [QuizController::class, 'getseed']);
        Route::post('/seed', [QuizController::class, 'seedquiz']);
        Route::get('/seed', [QuizController::class, 'seedquiz']);

        Route::get('/getcategory', [QuizController::class, 'getcategory']);
        Route::get('/categorygame', [QuizController::class, 'categoryquiz']);
        Route::post('/categorygame', [QuizController::class, 'categoryquiz']);

        Route::post('/ans', [QuizController::class, 'store']);
    });
});
=======
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
>>>>>>> 3435db419e1b57988185f5d2060c78375189396d

Route::group(['middleware' => ['admin']], function () {
    Route::get('admin-view', [AdminController::class, 'index'])->name('admin.view');

    Route::delete('/user/delete/{id}', [UserController::class, 'destroy']);

    Route::post('/category', [AdminController::class, 'store']);
    Route::delete('/category/delete/{id}', [AdminController::class, 'destroy_category']);

    Route::post('/update/answer/{id}', [AdminController::class, 'update_answer'])->name('answer.update');

    Route::post('/update/question/{id}', [QuestionController::class, 'update_question'])->name('question.update');
    Route::delete('/question/delete/{id}', [QuestionController::class, 'destroy_question']);

    Route::post('/approve/{id}', [QuestionController::class, 'approve_question'])->name('question.approve');
 });

 Auth::routes();

require __DIR__.'/auth.php';

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class UserController extends Controller
{
    public function show($id){
        $user = User::withCount(['questions'])->where('id', '=', $id)->first();

        $test = DB::table('users')->orderByDesc('xp')->get();// in prog

        $index = $this->findLeaderboardIndex($id, $test);

        return view('profile', ['user' => $user, 'index' => $index]);
    }

<<<<<<< HEAD
    public function findLeaderboardIndex($id, $arr){
        foreach(json_decode($arr, true) as $key => $object) {
            if($object['id'] == $id){
                return $key;
            }
        }
    }

    public function leaderboard(){
        $users = DB::table('users')->orderByDesc('xp')->limit(10)->get();
        return view('leaderboard', ['users' => $users]);
    }

=======
>>>>>>> 3435db419e1b57988185f5d2060c78375189396d
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.edit-user', ['user' => $user]);
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect('/admin-view#users/');
    }

    public function update($id)
    {
        $user = User::findOrFail($id);

        request()->validate([
            'name' => 'required',
            'email' => 'required',
        ]);

        $user -> name = request('name');
        $user -> email = request('email');

        if(request('is_active') != NULL){
            $user->is_active = '1';
        } else {
            $user->is_active = '0';
        }

        if(request('is_admin') != NULL){
            $user->is_admin = '1';
        } else {
            $user->is_admin = '0';
        }
        $user->save();

        return redirect()->back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <div class="full position-relative">
        <div class="p-6 d-flex justify-content-center"> 

            <h6>CHOOSE A GAME TYPE:</h6>
        </div>
        <div class="d-grid border border-secondary gap-2 col-6 mx-auto text-align: center">
            <a class="btn btn-outline-dark" type="button" href="/game">Arcade</a>
            <a class="btn btn-outline-dark" type="button" href="/getseed">Custom Seed</a>
            <a class="btn btn-outline-dark" type="button" href="/getcategory">Categories</a>
        </div>
    </div>
</x-app-layout>

resources/views/leaderboard.blade.php
<x-app-layout>
    <div class="container">
        <div class="py-2 d-flex justify-content-center"> 
            <h6>TOP 10:</h6>
        </div>
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 bg-white border-b border-gray-200">
                        <div class="p-5 border border-secondary">
                        <table class="table table-light table-bordered border-dark table-striped table-responsive-sm">
                            <thead>
                            <tr>
                                <th style="width:6%">Rank</th>
                                <th style="width:6%"></th>
                                <th>Name</th>
                                <th style="width:6%">Score</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                            <tr >
                                <td>{{ ($loop->index)+1 }}</td>
                                <td><img class="rounded" src="{{ $user->profile_pic }}" alt="pic" width="45" height="40"></td>
                                <td> {{$user->name}}</td>
                                <td>{{$user->xp}}</td>
                            </tr>
                                @endforeach
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>  
    </div>
</x-app-layout>

resources/views/profile.blade.php
<x-app-layout>
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
          <div class="col-md-20 text-center" id="app">
        	<div class="row">
        	  <div class = "col-4"></div>
	          <div class = "col-2">
				<img class="rounded" src="{{ $user->profile_pic }}" style="height: 125px !important">
		      </div>
		      <div class = "col-2" style="line-height: 40px">
				<p class="m-b-10">{{ $user->email }}</p>
	            <p><strong>{{ $user->name }}</strong></p>
	        	<div class="progress position-relative" style="background-color: #aaa; -webkit-box-shadow: none; box-shadow: none;">
  				  <div class="progress-bar" role="progressbar" style="width: {{ $user->xp%100 }}%" aria-valuemin="0" aria-valuemax="100"><small class="justify-content-center d-flex position-absolute w-100">{{ $user->xp%100 . '/100 XP' }}</small></div>
  				</div>
  				<span class="badge bg-primary">LVL {{ intval($user->xp/100) }}</span>
			  </div>
			  <div class = "col-4"></div>
            </div>
          </div>
        </div>
	  </div>
    </div>
  </div>
<div class="py-2 ">
	<div class="max-w-7xl mx-auto sm:px-6 lg:px-8 ">
		<div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
			<div class="p-6 bg-white border-b border-gray-200">
				<div class="container text-center">
					<div class="row align-items-start">
						<div class="col">
							<div class="card" style="width: 18rem;">
								<div class="card-header">Questions Created:</div>								
								<div class="card-body">
								  <p class="card-text">{{$user->questions_count}}</p>
								</div>
							</div>
						</div>
						<div class="col">
							<div class="card" style="width: 18rem;">
								<div class="card-header">Games Played:</div>								
								<div class="card-body">
								  <p class="card-text">{{$user->games_played}}</p>
								</div>
							</div>
						</div>
						<div class="col">
							<div class="card" style="width: 18rem;">
								<div class="card-header">Global Rank:</div>								
								<div class="card-body">
								  <p class="card-text">{{$index}}</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</x-app-layout>